steps:

  - task: DotNetCoreInstaller@0
    displayName: Use .NET Core SDK 2.1.301
    inputs:
      packageType: sdk
      version: '2.1.301'

  - task: InstallAppleCertificate@2
    displayName: Install kext certificate
    inputs:
      certSecureFile: PrjFSKextAug272018.p12
      certPwd: $(PrjFSKextCertPassword)
      keychain: temp

  - task: DownloadBuildArtifacts@0
    displayName: Download functional test drop
    inputs:
      buildType: current
      downloadType: specific
      artifactName: FunctionalTests_$(platformFriendlyName)_$(configuration)
      downloadPath: $(Build.BinariesDirectory)

  - bash: |
      chmod +x $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)/src/Scripts/Mac/*.sh
      chmod +x $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)/src/ProjFS.Mac/Scripts/*.sh
      chmod +x $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)/Publish/*
    displayName: Ensure tests assets are executable

  - bash: $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)/src/Scripts/Mac/PrepFunctionalTests.sh
    displayName: Prep functional tests

  - bash: |
      $AGENT_BUILDDIRECTORY/s/ProjFS.Mac/Scripts/LoadPrjFSKext.sh $(configuration)
      $AGENT_BUILDDIRECTORY/BuildOutput/ProjFS.Mac/Native/Build/Products/$(configuration)/prjfs-log > $BUILD_ARTIFACTSTAGINGDIRECTORY/kext.log 2>&1 &
    displayName: Enable kext logging

  - bash: $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)/src/Scripts/Mac/RunFunctionalTests.sh $(configuration)
    displayName: Run functional tests

  - task: PublishTestResults@2
    displayName: Publish functional test results
    inputs:
      testRunner: NUnit
      testResultsFiles: "**\\TestResult*.xml"
      searchFolder: $(System.DefaultWorkingDirectory)
      testRunTitle: macOS $(configuration) Functional Tests
      publishRunAttachments: true
    condition: succeededOrFailed()

  - bash: $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)/src/Scripts/Mac/CleanupFunctionalTests.sh
    displayName: Cleanup

  - task: PublishBuildArtifacts@1
    displayName: Publish kext logs
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)\kext.log
      artifactName: kext.log
    condition: succeededOrFailed()
