using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using System.IO;
using System.Text;

namespace GVFS.PreBuild
{
    public class GenerateUnifiedInstallScript : Task
    {
        [Required]
        public string G4WInstallerFilename { get; set; }

        [Required]
        public string GVFSSetupFilename { get; set; }

        [Required]
        public string OutputPath { get; set; }

        public override bool Execute()
        {
            this.Log.LogMessage(MessageImportance.High, "Creating install script for " + this.G4WInstallerFilename);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("REM AUTOGENERATED DO NOT EDIT");
            sb.AppendLine();
            sb.AppendLine("%~dp0\\" + this.G4WInstallerFilename + @" /DIR=""C:\Program Files\Git"" /NOICONS /COMPONENTS=""ext,ext\shellhere,ext\guihere,assoc,assoc_sh"" /GROUP=""Git"" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART");
            sb.AppendLine();
            sb.AppendLine("%~dp0\\" + this.GVFSSetupFilename + " /VERYSILENT /SUPPRESSMSGBOXES /NORESTART");

            File.WriteAllText(
                this.OutputPath,
                sb.ToString());

            return true;
        }
    }
}
