name: $(date:yy)$(DayOfYear)$(rev:.r)

trigger:
  - master
  - releases/shipped

variables:
  majorAndMinorVersion: '0.5'
  revision: '$(Build.BuildNumber)'

jobs:
  - job: Build_Windows
    variables:
      platformFriendlyName: Windows
    strategy:
      maxParallel: 2
      matrix:
        #debug:
        #  configuration: Debug
        release:
          configuration: Release
    pool:
      vmImage: vs2017-win2016
    steps:
    - template: templates/windows-build-and-unit-test.yml

  - job: Build_macOS
    variables:
      platformFriendlyName: macOS
    strategy:
      maxParallel: 2
      matrix:
        #debug:
        #  configuration: Debug
        release:
          configuration: Release
    pool:
      vmImage: macOS 10.13
    steps:
    - template: templates/macos-build-and-unit-test.yml

  - job: FunctionalTests_Windows
    variables:
      platformFriendlyName: Windows
      configuration: Release
    pool:
      name: FunctionalTests
    dependsOn: Build_Windows
    condition: succeeded()
    steps:
    - template: templates/windows-functional-test.yml