steps:
  - template: "templates/windows-build-and-unit-test.yml"
    parameters:
      BuildConfiguration: "$(BuildConfiguration)"
      MajorAndMinorVersion: "$(GVFSMajorAndMinorVersion)"
      Revision: "$(Build.BuildNumber)"
  - script: "echo hello world"